[package]
name = "do-something"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = "4.5.37"
serde = {version= "1.0.219", features = ["derive"]}
serde_json = "1.0.140"

[[bin]]
name = "ds"
path = "src/main.rs"
